import Head from 'next/head'
import {useState} from 'react'
import styled from 'styled-components'

const Counter = () =>{
  const [count, setCount] = useState(0)
  return(
    <Container>
      <CounterBox>{count}</CounterBox>
      <Increment onClick={()=> setCount(count+1)}>+</Increment>
      <Increment onClick={()=> setCount(0)}>Reset</Increment>
    </Container>
  )
}

export default function Home() {
  const [counters, setCounters] = useState([])

  const resetAllCounters = () =>{
    const newCounters = []
    counters.forEach(()=> newCounters.push(<Counter key={Math.random()}/>))
    setCounters(newCounters)
  }

  return (
    <BigBox >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NewCounter onClick={()=> setCounters([...counters,<Counter/>])}>Add New Counter</NewCounter>

      <NewCounter onClick={resetAllCounters}>Reset All</NewCounter>

      <CountersContainer>
        {counters}
      </CountersContainer>
    

    </BigBox>
  )
}

const BigBox = styled.div`
display:flex;
flex-direction:column;
justify-content: center;
align-items:center;
height:100vh;
text-align:center
`;


const Container = styled.div`
display:flex;
flex-direction:column;
padding: 30px 30px;
margin:0 15px 15px 15px;
background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(35,106,80,1) 35%, rgba(0,212,255,1) 100%);
`;

const CounterBox = styled.div`
  background-color:white;
  color:black;
  font-size;
  width:100px;
  padding:10px;
  margin-bottom:10px;
`;

const Increment = styled.button`
  font-size: 30px;
  padding: 5px 10px;
  width: 100px;
  color:white;
  background-color:#236a52;
  margin-bottom:10px;
  border-radius:5px;
  cursor: pointer;
  &:last-child{
    margin-bottom:0;
    font-size:20px
  }
`;

const NewCounter = styled.button`
font-size: 30px;
padding: 5px 10px;
min-width: 100px;
color:white;
background-color:#236a52;
margin-bottom:10px;
border-radius:5px;
cursor: pointer;
`;

const CountersContainer = styled.div`
  display:flex;
  flex-wrap:wrap;
  padding:20px;

`;